version: '3'
services:
  webserver:
    container_name: webserver
    image: nginx:latest
    ports:
      - "80:80"
    volumes:  
      - ./src:/usr/share/nginx/html
      # - ./css:/usr/share/nginx/css
      # - ./assets:/usr/share/nginx/assets
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./html-with-bootstrap:/usr/share/nginx/html/bootstrap
      # - ./css-with-bootstrap:/usr/share/nginx/css-bootstrap